:toc:       macro
:toclevels: 1
:toc-title:

image:https://img.shields.io/github/v/tag/pixelstuermer/pixieset-downloader[link=https://github.com/pixelstuermer/pixieset-downloader/tags]
image:https://img.shields.io/github/license/pixelstuermer/pixieset-downloader[link=LICENSE]
image:https://img.shields.io/badge/python-v3.9.6-blue[link=https://www.python.org/downloads/release/python-396] +
image:https://github.com/pixelstuermer/pixieset-downloader/actions/workflows/lint-python.yml/badge.svg[link=https://github.com/pixelstuermer/pixieset-downloader/actions/workflows/lint-python.yml]
image:https://github.com/pixelstuermer/pixieset-downloader/actions/workflows/asciidoc-gh-pages.yml/badge.svg[link=https://github.com/pixelstuermer/pixieset-downloader/actions/workflows/asciidoc-gh-pages.yml] +
image:https://img.shields.io/github/issues-pr/pixelstuermer/pixieset-downloader[link=https://github.com/pixelstuermer/pixieset-downloader/pulls]
image:https://img.shields.io/github/issues/pixelstuermer/pixieset-downloader[link=https://github.com/pixelstuermer/pixieset-downloader/issues]

image:https://forthebadge.com/images/badges/works-on-my-machine.svg[link=https://forthebadge.com]

[discrete]
= pixieset-downloader

Batch download of Pixieset collections. +
See https://pixelstuermer.github.io/pixieset-downloader[GitHub pages] or https://github.com/pixelstuermer/pixieset-downloader[GitHub project].

toc::[]

== TL;DR

Download the https://github.com/pixelstuermer/pixieset-downloader/tags[latest release] and install https://www.python.org/downloads/release/python-396[Python 3.9.6], then switch to the root directory and run `pip install -r requirements.txt`.
Find out the required arguments `base_url`, `collection_id`, `collection_key`, `gallery_name` and obtain a valid HTTP session `cookie`.
The optional arguments `--filename`, `--separator` and `--regex` can specify the images to download and the target file names.

Then run the following:

----
python pixieset-downloader.py [-f FILENAME] [-s SEPARATOR] [-r REGEX] base_url collection_id collection_key gallery_name cookie
----

Or run the following for CLI usage help:

----
python pixieset-downloader.py -h
----

== About

Tbd.

== Requirements

Built with/for https://www.python.org/downloads/release/python-396[Python 3.9.6].
The required packages can be easily installed by running `pip install -r requirements.txt` before executing the script.

== How To Use

Tbd.

== Required Arguments

Tbd.

== Examples

Tbd.

== Limitations

The downloaded images might still be watermarked and are maybe with lower quality than the originals – which is good to support your local photographers!
It is also not guaranteed that absolutely all images have been downloaded, so this should be verified manually.

== Changelog

=== https://github.com/pixelstuermer/pixieset-downloader/tree/1.0.0[1.0.0] (2021-08-14)

==== Added

* Basic functionality and project setup
* Batch download of Pixieset collections
** Based on a base url, a collection ID and key, a gallery name and a valid HTTP cookie
** With the possibility to specify target file names and a counter separator
** With an optional filter for image names via RegEx
